2 Hop bridging using stargate, improvements/refactoring in  direct bridge code
hubble-exchange/hubble-protocol pull request #159
Opened 2023-05-19 12:38 UTC by sunnyRK

- This commit consists mechanism for multichain tokens swap/transfer
- From AnyEVM Chain -> CChain -> Hubblenet
- In case of 2 hops tx, fees required for 2nd hop is deducted from usdc transferred
- Main test-cases added but need to add more test-cases.

2023-06-21 13:33 UTC, asquare08 requested changes

2023-06-21 13:33 UTC, asquare08 commented on test/socketRouterTests.js
> +
lets assert the event args as well

2023-06-21 13:33 UTC, asquare08 commented on test/socketRouterTests.js
> +                .to.emit(hgtRemoteAvax, 'SendToChain')
assert event args

2023-06-21 18:21 UTC, asquare08 commented on test/socketRouterTests.js
> +            const fees = await hgt.estimateSendFee(
shouldn't it be hgtRemote?

2023-06-21 18:26 UTC, asquare08 commented on test/socketRouterTests.js
> +const fromAmount = '1000000'
lets test it with 100 usdc

2023-06-26 18:52 UTC, asquare08 commented on contracts/Interfaces.sol
> +        uint gasToken;
lets write precision of both here in commnet

2023-06-26 18:52 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            if (deductUsdc > _amountLD || (_amountLD - deductUsdc) < sendVars.gasToken) {
add equality in `deductUsdc >= _amountLD` so that we don't transfer 0 amount

2023-06-26 18:52 UTC, asquare08 commented on contracts/HGTCore.sol
> +            // It calls while withdraw fund from Hubblenet
change the comment to `It is called while withdrawing funds from hubbleNet to anyEVMChain (other than direct bridge chain)`

2023-06-26 18:52 UTC, asquare08 commented on contracts/HGTCore.sol
> +            // It calls while deposit fund from anyEvmChain
Change the comment to `It is called when depositing funds from anyEVMChain (including the direct bridge chain) to hubbleNet`

2023-06-26 18:52 UTC, asquare08 commented on contracts/HGT.sol
> +                marginAccountHelper.addVUSDMarginWithReserve{value: _amount}(_amount, _toAddress);
amount in these 2 functions is in 1e6. maybe we have to define another variable amountScaled and also update events to emit amount, gastoken and isInsuranceFund values

2023-06-26 18:52 UTC, asquare08 commented on contracts/HGT.sol
> +        _gasToken *= SCALING_FACTOR;
can be moved inside if statement

2023-06-29 11:44 UTC, atvanguard requested changes

2023-06-29 11:44 UTC, atvanguard commented on contracts/HGT.sol
>      function _debitFrom(address, uint _amount) internal virtual override returns(uint) {
line 41 is not needed because solidity compiler already performs overflow check when doing addition/subtraction

2023-06-30 12:10 UTC, asquare08 commented on contracts/HGT.sol
>      function _debitFrom(address, uint _amount) internal virtual override returns(uint) {
removed

2023-07-02 08:25 UTC, asquare08 commented on contracts/HGTCore.sol
> +        bool _NeedTreansferFrom,
fixed

2023-07-02 11:58 UTC, atvanguard requested changes
Generally, unhappy with the tests, There's lots of code duplication and very liberal use of _magic numbers_ - in code review terminology magic number is using a hardcoded number without it being obvious what that number means in that context.

2023-07-02 11:58 UTC, atvanguard commented on contracts/HGTRemote.sol
> +            (uint256 fees,) = stargateRouter.quoteLayerZeroFee(_dstChainId, TYPE_SWAP_REMOTE, _toAddress, new bytes(0), IStargateRouter.lzTxObj(0, 0, "0x"));
what if the _dstChainId is invalid

2023-07-02 11:58 UTC, atvanguard commented on contracts/HGTRemote.sol
> +            if (deductUsdc > _amount) {
and `==`? will stargate allow transferring 0 amount?

2023-07-02 11:58 UTC, atvanguard commented on test/CrossChainTests.js
> +                BigNumber.from(hgtBalanceBefore).add(parseEther('100'))
please don't use magic numbers. why not use `fromAmountForWithdraw` instead of `parseEther('100)`

2023-07-02 11:58 UTC, atvanguard commented on test/CrossChainTests.js
> +            it('Withdraw Hop2 fails and execute rescueUserFundsForWithdraw', async () => {
almost the same as above

2023-07-02 11:58 UTC, atvanguard commented on test/CrossChainTests.js
> +            it('rescueUserFundsForWithdraw if small withdraw happen', async () => {
same as the test above the test above this

2023-07-02 11:58 UTC, atvanguard commented on test/CrossChainTests.js
> +        it('with gasToken amount and isInsuranceFund=true', async () => {
this test should also check users IF balance.

2023-07-03 06:08 UTC, asquare08 commented on contracts/HGT.sol
> +    function _creditTo(address _toAddress, uint _amount, uint256 _gasToken, bool _isInsuranceFund) internal virtual override whenNotPaused returns(uint) {
as discussed, this is difficult to implement for 2 hop txs

2023-07-03 06:09 UTC, asquare08 commented on contracts/HGT.sol
> +        return _amount *= SCALING_FACTOR;
fixed

2023-07-03 06:09 UTC, asquare08 commented on contracts/HGTCore.sol
>      function _nonblockingLzReceive(uint16 _srcChainId, bytes memory _srcAddress, uint64 _nonce, bytes memory _payload) internal virtual override {
removed inheritance of HGTCore from HGT and implemented separate functions for HGT

2023-07-03 06:11 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            from, sendVars.dstChainId, sendVars.gasToken, sendVars.isInsuranceFund, sendVars.to,
since it'll require more inventory management on CChain side for 2 hops, we'll use gasToken method

2023-07-03 06:11 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            storeFailedFundsForDeposit(_amountLD, sendVars.to, sendVars.dstChainId);
changed

2023-07-03 06:12 UTC, asquare08 commented on contracts/HGTRemote.sol
> +                    0,
added `amountMin` argument for withdraws

2023-07-03 06:12 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            (uint nativeFee,) = this.estimateSendFee(sendVars, 0, false);
fixed

2023-07-03 06:13 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            if (deductUsdc > _amount) {
right. added equality

2023-07-03 06:14 UTC, asquare08 commented on contracts/HGTRemote.sol
> +                    isNextCall = true;
renamed.

2023-07-03 06:14 UTC, asquare08 commented on contracts/HGT.sol
> +                marginAccountHelper.addVUSDMarginWithReserve{value: amountScaled}(amountScaled / SCALING_FACTOR, _toAddress);
updated

2023-07-03 06:26 UTC, asquare08 commented on contracts/HGTRemote.sol
> +    * layer0 is duducted from the amount transferred
fixed

2023-07-03 06:35 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            uint256 deductUsdc = nativeFee * uint(latestPrice) / BASE_PRECISION;
added a state variable to track this

2023-07-03 06:38 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            (uint nativeFee,) = this.estimateSendFee(sendVars, 0, false);
yes, it can happen that the actual fee turns out to be more than estimated, in that case layer0 relayer pays for it and in the opposite case, layer0 ralyer keeps it. However, if more fee is sent than estimated, it is refunded back

2023-07-03 07:57 UTC, asquare08 commented on contracts/HGTRemote.sol
> +            (uint256 fees,) = stargateRouter.quoteLayerZeroFee(_dstChainId, TYPE_SWAP_REMOTE, _toAddress, new bytes(0), IStargateRouter.lzTxObj(0, 0, "0x"));
it will revert. added try/catch here

2023-07-14 08:46 UTC, atvanguard reviewed
- Made some comments
- Please move HGT.sol and HGTRemote.sol to a new folder called `layer0`
- Resolve conflicts with main

2023-07-14 08:46 UTC, atvanguard commented on contracts/HGT.sol
> +        uint64 nonce = lzEndpoint.getOutboundNonce(vars.dstChainId, address(this));
this should come before the line above.

2023-07-14 08:46 UTC, atvanguard commented on test/bridge/WithdrawTests.js
> +            expect(await hgtRemote.feeCollected(0)).to.eq(stargateFee)
also assert `usdcAvaxInstance.balanceOf(alice)`?

2023-07-14 10:50 UTC, asquare08 commented on test/bridge/WithdrawTests.js
> +            expect(await hgtRemote.feeCollected(0)).to.eq(stargateFee)
we cannot assert the final balance of alice (on eth mainnet) in this case as it'll be transferred by stargate. added an assertion for ccchain balance

2023-07-14 10:55 UTC, asquare08 commented on contracts/HGT.sol
> +        uint64 nonce = lzEndpoint.getOutboundNonce(vars.dstChainId, address(this));
I think this should come after only in both HGT and hgtRemote because outBound nonce is increased during lzSend and same is sent to lzReceive. So it'll be better get the nonce after the tx to match the events related to same tx.

2023-07-14 10:57 UTC, asquare08 commented on contracts/HGTRemote.sol
> +        nativeTokenPrice = getLatestRoundData(supportedTokens[USDC_IDX].priceFeed);
I assumed price to be in USDC terms and not USD, that's why USDC price didn't occur to my mind. But now I checked, the price is in USD actually, changed the code accordingly.

2023-07-14 10:57 UTC, asquare08 commented on test/bridge/bridgeUtils.js
> +            priceFeed: priceFeedAvaxToUSDC,
changed

2023-07-14 10:57 UTC, asquare08 commented on test/bridge/bridgeUtils.js
> +const priceFeedAvaxToUSDC = '0x0A77230d17318075983913bC2145DB16C7366156' // from Chainkink avax net
changed

2023-07-14 15:51 UTC, atvanguard approved these changes

2023-07-14 16:03 UTC, asquare08 commented on contracts/layer0/HGTRemote.sol
>      function quoteStargateFeeInUSD(uint16 _dstChainId, uint8 _functionType, bytes calldata _toAddress,  bytes calldata _transferAndCallPayload, IStargateRouter.lzTxObj memory _lzTxParams) external vi
it'll be used in FE to calculate stargate fee while withdrawing

2023-07-14 16:04 UTC, asquare08 commented on contracts/MarginAccountHelper.sol
> +    function withdrawMarginToChain(uint amount, uint tokenIdx, uint16 directBridgeChainId, uint16 dstChainId, uint amountMin, uint dstPoolId) external {
yeah added a comment for this

2023-07-14 16:26 UTC, merged