add FeeSink contract and tests
hubble-exchange/hubble-protocol pull request #178
Opened 2023-07-18 09:56 UTC by fdgod09

2023-07-19 07:56 UTC, asquare08 commented on contracts/FeeSink.sol
> +        if (openInterest <= 0) {
only `=` is enough

2023-07-19 07:56 UTC, asquare08 commented on contracts/FeeSink.sol
> +    uint public insuranceFundToOpenInterestTargetRatio;
please add a comment explaining the these variables and their precison too

2023-07-19 07:56 UTC, asquare08 commented on contracts/FeeSink.sol
> +        insuranceFundFee = (((insuranceFundToOpenInterestTargetRatio * feeAmount) - ((insuranceFundBalance * feeAmount * 1e6) / openInterest)) * maxFeePercentageForInsuranceFund) / 1e12;
this can be simplified as `(insuranceFundToOpenInterestTargetRatio - insuranceFundToOpenInterestRatio) * feeAmount * maxFeePercentageForInsuranceFund / 1e12` as BODMAS rule is followed.

2023-07-19 07:56 UTC, asquare08 commented on contracts/FeeSink.sol
> +    function distributeFunds() external onlyGovernance {
please add few lines of comment explaining the distribution strategy

2023-07-19 07:56 UTC, asquare08 commented on contracts/FeeSink.sol
> +        if (insuranceFundFee <= 0) {
I think condition will never arise because of checks in line 91, 79 and 71.

2023-07-19 07:56 UTC, asquare08 commented on test/utils.js
> +const DEFAULT_TREASURY_ADDRESS = "0x22Bb736b64A0b4D4081E103f83bccF864F0404aa" // change this
this can be taken in `options` argument of `setupContracts`

2023-07-19 07:56 UTC, asquare08 commented on test/utils.js
> +    constants: { _1e6, _1e8, _1e12, _1e18, ZERO, feeSink: defaultFeeSink.address, defaultTreasuryAddress: DEFAULT_TREASURY_ADDRESS },
we can use the feeSink contract in rest of the tests as well and remove the default one.

2023-07-20 07:18 UTC, asquare08 approved these changes

2023-07-20 07:18 UTC, asquare08 commented on contracts/FeeSink.sol
> +    */
let's change it to this for better readability 
```
   /**
     * @notice Distributes the funds in the contract to the insurance fund and treasury.
     * let x = Insurance fund balance (IF) / Open interest (OI), y = target IF / OI ratio, z = maxFeePercentage to insurance fund
     * if x < y, funds are distributed between insurance fund and treasury as per below formula
     * insurance fund share = (1 - x / y) * z * feeAmount
     * rest is sent to the treasury.
     * if either y or z is 0, all funds are sent to the treasury.
     * if x >= y, all funds are sent to the treasury.
     * Can only be called by the governance.
     * @dev reverts if no funds are available to distribute.
    */

2023-07-20 07:18 UTC, asquare08 commented on contracts/FeeSink.sol
> +        insuranceFundFee = ((1e6 -  (insuranceFundToOpenInterestRatio * 1e6 / insuranceFundToOpenInterestTargetRatio)) * feeAmount * maxFeePercentageForInsuranceFund) / 1e12;
this can be simplified to this, saves 1 operation 
```
(insuranceFundToOpenInterestTargetRatio -  insuranceFundToOpenInterestRatio) * maxFeePercentageForInsuranceFund * feeAmount / insuranceFundToOpenInterestTargetRatio  / 1e6;

2023-07-20 09:30 UTC, atvanguard requested changes

2023-07-20 09:30 UTC, atvanguard commented on contracts/FeeSink.sol
> +    ClearingHouse public clearingHouse;
Will never change. should be immutable.

2023-07-20 09:30 UTC, atvanguard commented on contracts/FeeSink.sol
> +    }
not required. these can be immutable.

2023-07-20 09:30 UTC, atvanguard commented on contracts/FeeSink.sol
> +    function distributeFunds() external onlyGovernance {
this should be callable by either governance or a whitelisted account - so that we can automate it. whereas governance account will be a hardware wallet. See HubbleReferral for inspiration.

2023-07-20 09:33 UTC, atvanguard commented
nit: we keep the `onlyGovernance` actions to the end of the contract so that business logic appears first. slightly better for readability.

2023-07-23 13:05 UTC, atvanguard requested changes
So this PR has a fatal flaw that `openInterestNotional` is denominated in the asset being traded whereas `insuranceFundBalance` is in vusd. Also the former has 18 decimals and latter has 6 decimals and the test only passes because it has been set up with very large value in line 258.

2023-07-24 14:05 UTC, atvanguard approved these changes

2023-07-24 14:05 UTC, merged